### ISSUE TITLE
Ensure drop-in installer (installation flags)

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#1019]
This is a list of flags that must be supported in the `elemental install` command to ensure a drop-in replacement with the current bash installer.

It roughly matches the `TODO`s from `pkg/action/install.go`

Installer flags:
 - [x] --docker-image https://github.com/rancher-sandbox/elemental-cli/pull/34
 - [x] --no-verify https://github.com/rancher-sandbox/elemental-cli/pull/34
 - [x] --no-cosign https://github.com/rancher-sandbox/elemental-cli/pull/34
 - [x] --no-format rancher-sandbox/elemental-cli#32
 - [x] --force-efi rancher-sandbox/elemental-cli#32
 - [x] --force
 - [x] --force-gpt rancher-sandbox/elemental-cli#32
 - [x] ~--power-off~ (not implemented as this is not effective in [cos-installer](https://github.com/rancher-sandbox/cOS-toolkit/blob/177ef04cfa29cfe67bc264fa2307684d84b35323/packages/installer/cos.sh#L1482-L1492), its always run in interactive mode)
 - [x] --strict rancher-sandbox/elemental-cli#32
 - [x] --debug (should be coded at logging setup level) https://github.com/rancher-sandbox/elemental-cli/issues/37
 - [x] --config (downloads a cloudinit file from URL and stores it in OEM partitions `/oem/99_custom`)
 - [x] --partition-layout
 - [x] --iso https://github.com/rancher-sandbox/elemental-cli/pull/41
 - [x] --tty
 - [x] -h
 - [x] --help

Installer behavior:
 - [x] #1050
 - [x] #1064

**Comment by Itxaka** [comment]
debug done as part of https://github.com/rancher-sandbox/elemental-cli/pull/38

**Comment by davidcassany** [comment]
This list kept growing as more and more I got into the `/packages/installer/cos.sh` code. Hopefully I believe we are really into the last mile and no further items will be added. Regarding #1054 and #1059 it is arguable this is something actually required as a drop in replacement and #1064 should not take much to implement. I hope we can close this card during next planning and focus on follow up steps to dropping `cos-installer` script and required integration tests to validate it.

**Comment by davidcassany** [comment]
Done
