### ISSUE TITLE
Build Cloud images with Packer

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#208]
**Is your feature request related to a problem? Please describe.**
Although #174 specifically refers to a KIWI-oriented solution, it's still a good idea to provide Packer templates. Those are well known and easy to edit for everyone, and would definitely improve the  user UX.

**Describe the solution you'd like**
Packer templates for building cloud images. See https://github.com/rancher-sandbox/cOS-toolkit/issues/174#issuecomment-844172842 for references

The templates should ideally reuse the vanilla images (created with https://github.com/rancher-sandbox/cOS-toolkit/pull/235 ) to build up new images with the user container images

- [x] AWS - https://github.com/rancher-sandbox/cOS-toolkit/issues/302
- [x] Azure - https://github.com/rancher-sandbox/cOS-toolkit/issues/341
- [x] GCP - https://github.com/rancher-sandbox/cOS-toolkit/issues/380
- [ ] #451
- [ ] #452
- [ ] #453
- [x] Vagrant-libvirt
- [x] #455
- [ ] #454

**Describe alternatives you've considered**

**Additional context**
See also https://github.com/rancher/k3os/tree/master/package/packer

**Comment by mudler** [comment]
Blocked by #235

**Comment by mudler** [comment]
Major cloud providers were covered, I've opened separate issues for the remaining ones to tackle them individually in case we need them
