### ISSUE TITLE
Building cOS Cloud Images

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#217]
This is an epic issue to track the progress on image building for Public Clouds. This is mostly based on the ideas exposed in https://github.com/rancher-sandbox/cOS-toolkit/issues/174#issuecomment-843324824 and with the very rough PoC living in [image_builder](https://github.com/rancher-sandbox/cOS-toolkit/tree/image_builder) branch. 

Issues:
- [x] Test and boot the PoC img in AWS (fine tune grub2 configuration, serial console, etc.) #218
- [x] Separate recovery img from the system image #192
- [x] Repartition options in YIP #219
- [x] Deploy image in COS_ACTIVE #220
- [x] Test and boot the PoC img in Azure #221
- [x] Test and boot the PoC img in Google Cloud #222
- [x] #449
- [x] Integrate the image-builder into cOS-Toolkit and CI workflows
- [x] #450

See also:
- Integration of Vanilla images with packer for custom appliances #208

**Comment by mudler** [comment]
Closing this issue, I've created #450 and #449 for follow-ups
