### ISSUE TITLE
Handling image mirroring to different registries

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#6]
- [x] https://github.com/mudler/luet/issues/158
- [x] https://github.com/mudler/luet/issues/162
- [x] https://github.com/mudler/luet/issues/161
- [x] https://github.com/mudler/luet/issues/185
